export type MalariaRisk = "high" | "moderate" | "low" | "none";

// Keys must match the NAME property from countries.geojson exactly
export const malariaRiskByCountry: Record<string, MalariaRisk> = {
  // ── Africa ──
  "Nigeria": "high",
  "Dem. Rep. Congo": "high",
  "Uganda": "high",
  "Mozambique": "high",
  "Niger": "high",
  "Burkina Faso": "high",
  "Mali": "high",
  "Angola": "high",
  "Tanzania": "high",
  "Ghana": "high",
  "Cameroon": "high",
  "Côte d'Ivoire": "high",
  "Guinea": "high",
  "Malawi": "high",
  "Benin": "high",
  "Zambia": "high",
  "Sierra Leone": "high",
  "Chad": "high",
  "Burundi": "high",
  "Togo": "high",
  "Senegal": "high",
  "Central African Rep.": "high",
  "Rwanda": "high",
  "S. Sudan": "high",
  "Somalia": "high",
  "Liberia": "high",
  "Guinea-Bissau": "high",
  "Eq. Guinea": "high",
  "Gabon": "moderate",
  "Congo": "moderate",
  "Gambia": "high",
  "Mauritania": "moderate",
  "Comoros": "moderate",
  "Kenya": "moderate",
  "Zimbabwe": "moderate",
  "Madagascar": "moderate",
  "Sudan": "high",
  "Eritrea": "moderate",
  "Ethiopia": "moderate",
  "Djibouti": "low",
  "Botswana": "low",
  "Namibia": "low",
  "South Africa": "low",
  "eSwatini": "low",
  "Cape Verde": "low",

  // ── Asia ──
  "India": "moderate",
  "Pakistan": "moderate",
  "Bangladesh": "low",
  "Myanmar": "moderate",
  "Indonesia": "moderate",
  "Papua New Guinea": "high",
  "Cambodia": "low",
  "Laos": "low",
  "Vietnam": "low",
  "Thailand": "low",
  "Philippines": "low",
  "Malaysia": "low",
  "Nepal": "low",
  "Bhutan": "low",
  "Timor-Leste": "moderate",
  "Afghanistan": "moderate",
  "Yemen": "moderate",
  "Saudi Arabia": "low",
  "Iran": "low",
  "Iraq": "low",
  "China": "low",
  "North Korea": "low",
  "South Korea": "low",
  "Tajikistan": "low",

  // ── Americas ──
  "Brazil": "moderate",
  "Venezuela": "moderate",
  "Colombia": "moderate",
  "Peru": "low",
  "Ecuador": "low",
  "Bolivia": "low",
  "Guyana": "moderate",
  "Suriname": "low",
  "Paraguay": "low",
  "Haiti": "moderate",
  "Dominican Rep.": "low",
  "Guatemala": "low",
  "Honduras": "low",
  "Nicaragua": "low",
  "Panama": "low",
  "Costa Rica": "low",
  "Belize": "low",
  "Mexico": "low",

  // ── Oceania ──
  "Solomon Is.": "high",
  "Vanuatu": "moderate",
};

export const MALARIA_COLORS: Record<MalariaRisk, string> = {
  high: "rgba(239, 68, 68, 0.7)",
  moderate: "rgba(245, 158, 11, 0.6)",
  low: "rgba(250, 204, 21, 0.45)",
  none: "rgba(0, 0, 0, 0)",
};

export const MALARIA_LEGEND = [
  { level: "high", label: "High risk", color: "rgba(239, 68, 68, 0.85)" },
  { level: "moderate", label: "Moderate risk", color: "rgba(245, 158, 11, 0.8)" },
  { level: "low", label: "Low / limited risk", color: "rgba(250, 204, 21, 0.7)" },
  { level: "none", label: "No malaria", color: "rgba(100, 116, 139, 0.3)" },
];
