export const SUPPORTED_COUNTRIES = {
  // ── Africa ──
  angola: { label: "Angola", lat: -11.20, lng: 17.87, flag: "🇦🇴", region: "Central Africa", continent: "Africa" },
  benin: { label: "Benin", lat: 9.31, lng: 2.31, flag: "🇧🇯", region: "West Africa", continent: "Africa" },
  botswana: { label: "Botswana", lat: -22.33, lng: 24.68, flag: "🇧🇼", region: "Southern Africa", continent: "Africa" },
  "burkina-faso": { label: "Burkina Faso", lat: 12.36, lng: -1.56, flag: "🇧🇫", region: "West Africa", continent: "Africa" },
  burundi: { label: "Burundi", lat: -3.37, lng: 29.92, flag: "🇧🇮", region: "East Africa", continent: "Africa" },
  cameroon: { label: "Cameroon", lat: 7.37, lng: 12.35, flag: "🇨🇲", region: "Central Africa", continent: "Africa" },
  "cape-verde": { label: "Cape Verde", lat: 16.00, lng: -24.01, flag: "🇨🇻", region: "West Africa", continent: "Africa" },
  "central-african-republic": { label: "Central African Rep.", lat: 6.61, lng: 20.94, flag: "🇨🇫", region: "Central Africa", continent: "Africa" },
  chad: { label: "Chad", lat: 15.45, lng: 18.73, flag: "🇹🇩", region: "Central Africa", continent: "Africa" },
  comoros: { label: "Comoros", lat: -11.88, lng: 43.87, flag: "🇰🇲", region: "East Africa", continent: "Africa" },
  congo: { label: "Congo", lat: -0.23, lng: 15.83, flag: "🇨🇬", region: "Central Africa", continent: "Africa" },
  "dr-congo": { label: "Dem. Rep. Congo", lat: -4.04, lng: 21.76, flag: "🇨🇩", region: "Central Africa", continent: "Africa" },
  "cote-divoire": { label: "Côte d'Ivoire", lat: 7.54, lng: -5.55, flag: "🇨🇮", region: "West Africa", continent: "Africa" },
  djibouti: { label: "Djibouti", lat: 11.83, lng: 42.59, flag: "🇩🇯", region: "East Africa", continent: "Africa" },
  egypt: { label: "Egypt", lat: 26.82, lng: 30.80, flag: "🇪🇬", region: "North Africa", continent: "Africa" },
  "equatorial-guinea": { label: "Eq. Guinea", lat: 1.65, lng: 10.27, flag: "🇬🇶", region: "Central Africa", continent: "Africa" },
  eritrea: { label: "Eritrea", lat: 15.18, lng: 39.78, flag: "🇪🇷", region: "East Africa", continent: "Africa" },
  ethiopia: { label: "Ethiopia", lat: 9.15, lng: 40.49, flag: "🇪🇹", region: "East Africa", continent: "Africa" },
  gabon: { label: "Gabon", lat: -0.80, lng: 11.61, flag: "🇬🇦", region: "Central Africa", continent: "Africa" },
  gambia: { label: "Gambia", lat: 13.44, lng: -15.31, flag: "🇬🇲", region: "West Africa", continent: "Africa" },
  ghana: { label: "Ghana", lat: 7.95, lng: -1.02, flag: "🇬🇭", region: "West Africa", continent: "Africa" },
  guinea: { label: "Guinea", lat: 9.95, lng: -9.70, flag: "🇬🇳", region: "West Africa", continent: "Africa" },
  "guinea-bissau": { label: "Guinea-Bissau", lat: 11.80, lng: -15.18, flag: "🇬🇼", region: "West Africa", continent: "Africa" },
  kenya: { label: "Kenya", lat: -0.02, lng: 37.91, flag: "🇰🇪", region: "East Africa", continent: "Africa" },
  liberia: { label: "Liberia", lat: 6.43, lng: -9.43, flag: "🇱🇷", region: "West Africa", continent: "Africa" },
  madagascar: { label: "Madagascar", lat: -18.77, lng: 46.87, flag: "🇲🇬", region: "East Africa", continent: "Africa" },
  malawi: { label: "Malawi", lat: -13.25, lng: 34.30, flag: "🇲🇼", region: "East Africa", continent: "Africa" },
  mali: { label: "Mali", lat: 17.57, lng: -4.00, flag: "🇲🇱", region: "West Africa", continent: "Africa" },
  mauritania: { label: "Mauritania", lat: 21.01, lng: -10.94, flag: "🇲🇷", region: "West Africa", continent: "Africa" },
  mozambique: { label: "Mozambique", lat: -18.67, lng: 35.53, flag: "🇲🇿", region: "East Africa", continent: "Africa" },
  namibia: { label: "Namibia", lat: -22.96, lng: 18.49, flag: "🇳🇦", region: "Southern Africa", continent: "Africa" },
  niger: { label: "Niger", lat: 17.61, lng: 8.08, flag: "🇳🇪", region: "West Africa", continent: "Africa" },
  nigeria: { label: "Nigeria", lat: 9.08, lng: 8.68, flag: "🇳🇬", region: "West Africa", continent: "Africa" },
  rwanda: { label: "Rwanda", lat: -1.94, lng: 29.87, flag: "🇷🇼", region: "East Africa", continent: "Africa" },
  senegal: { label: "Senegal", lat: 14.50, lng: -14.45, flag: "🇸🇳", region: "West Africa", continent: "Africa" },
  "sierra-leone": { label: "Sierra Leone", lat: 8.46, lng: -11.78, flag: "🇸🇱", region: "West Africa", continent: "Africa" },
  somalia: { label: "Somalia", lat: 5.15, lng: 46.20, flag: "🇸🇴", region: "East Africa", continent: "Africa" },
  "south-africa": { label: "South Africa", lat: -30.56, lng: 22.94, flag: "🇿🇦", region: "Southern Africa", continent: "Africa" },
  "south-sudan": { label: "S. Sudan", lat: 6.88, lng: 31.31, flag: "🇸🇸", region: "East Africa", continent: "Africa" },
  sudan: { label: "Sudan", lat: 12.86, lng: 30.22, flag: "🇸🇩", region: "North Africa", continent: "Africa" },
  tanzania: { label: "Tanzania", lat: -6.37, lng: 34.89, flag: "🇹🇿", region: "East Africa", continent: "Africa" },
  togo: { label: "Togo", lat: 8.62, lng: 0.82, flag: "🇹🇬", region: "West Africa", continent: "Africa" },
  uganda: { label: "Uganda", lat: 1.37, lng: 32.29, flag: "🇺🇬", region: "East Africa", continent: "Africa" },
  zambia: { label: "Zambia", lat: -13.13, lng: 27.85, flag: "🇿🇲", region: "East Africa", continent: "Africa" },
  zimbabwe: { label: "Zimbabwe", lat: -19.02, lng: 29.15, flag: "🇿🇼", region: "Southern Africa", continent: "Africa" },
  eswatini: { label: "eSwatini", lat: -26.52, lng: 31.47, flag: "🇸🇿", region: "Southern Africa", continent: "Africa" },

  // ── Asia ──
  afghanistan: { label: "Afghanistan", lat: 33.94, lng: 67.71, flag: "🇦🇫", region: "Central Asia", continent: "Asia" },
  bangladesh: { label: "Bangladesh", lat: 23.68, lng: 90.36, flag: "🇧🇩", region: "South Asia", continent: "Asia" },
  bhutan: { label: "Bhutan", lat: 27.51, lng: 90.43, flag: "🇧🇹", region: "South Asia", continent: "Asia" },
  cambodia: { label: "Cambodia", lat: 12.57, lng: 104.99, flag: "🇰🇭", region: "Southeast Asia", continent: "Asia" },
  china: { label: "China", lat: 35.86, lng: 104.20, flag: "🇨🇳", region: "East Asia", continent: "Asia" },
  india: { label: "India", lat: 20.59, lng: 78.96, flag: "🇮🇳", region: "South Asia", continent: "Asia" },
  indonesia: { label: "Indonesia", lat: -0.79, lng: 113.92, flag: "🇮🇩", region: "Southeast Asia", continent: "Asia" },
  iran: { label: "Iran", lat: 32.43, lng: 53.69, flag: "🇮🇷", region: "Western Asia", continent: "Asia" },
  iraq: { label: "Iraq", lat: 33.22, lng: 43.68, flag: "🇮🇶", region: "Western Asia", continent: "Asia" },
  laos: { label: "Laos", lat: 19.86, lng: 102.50, flag: "🇱🇦", region: "Southeast Asia", continent: "Asia" },
  malaysia: { label: "Malaysia", lat: 4.21, lng: 101.98, flag: "🇲🇾", region: "Southeast Asia", continent: "Asia" },
  myanmar: { label: "Myanmar", lat: 21.91, lng: 95.96, flag: "🇲🇲", region: "Southeast Asia", continent: "Asia" },
  nepal: { label: "Nepal", lat: 28.39, lng: 84.12, flag: "🇳🇵", region: "South Asia", continent: "Asia" },
  "north-korea": { label: "North Korea", lat: 40.34, lng: 127.51, flag: "🇰🇵", region: "East Asia", continent: "Asia" },
  pakistan: { label: "Pakistan", lat: 30.38, lng: 69.35, flag: "🇵🇰", region: "South Asia", continent: "Asia" },
  philippines: { label: "Philippines", lat: 12.88, lng: 121.77, flag: "🇵🇭", region: "Southeast Asia", continent: "Asia" },
  "saudi-arabia": { label: "Saudi Arabia", lat: 23.89, lng: 45.08, flag: "🇸🇦", region: "Western Asia", continent: "Asia" },
  "south-korea": { label: "South Korea", lat: 35.91, lng: 127.77, flag: "🇰🇷", region: "East Asia", continent: "Asia" },
  tajikistan: { label: "Tajikistan", lat: 38.86, lng: 71.28, flag: "🇹🇯", region: "Central Asia", continent: "Asia" },
  thailand: { label: "Thailand", lat: 15.87, lng: 100.99, flag: "🇹🇭", region: "Southeast Asia", continent: "Asia" },
  "timor-leste": { label: "Timor-Leste", lat: -8.87, lng: 125.73, flag: "🇹🇱", region: "Southeast Asia", continent: "Asia" },
  vietnam: { label: "Vietnam", lat: 14.06, lng: 108.28, flag: "🇻🇳", region: "Southeast Asia", continent: "Asia" },
  yemen: { label: "Yemen", lat: 15.55, lng: 48.52, flag: "🇾🇪", region: "Western Asia", continent: "Asia" },

  // ── Americas ──
  belize: { label: "Belize", lat: 17.19, lng: -88.50, flag: "🇧🇿", region: "Central America", continent: "Central America & Caribbean" },
  bolivia: { label: "Bolivia", lat: -16.29, lng: -63.59, flag: "🇧🇴", region: "South America", continent: "South America" },
  brazil: { label: "Brazil", lat: -14.24, lng: -51.93, flag: "🇧🇷", region: "South America", continent: "South America" },
  colombia: { label: "Colombia", lat: 4.57, lng: -74.30, flag: "🇨🇴", region: "South America", continent: "South America" },
  "costa-rica": { label: "Costa Rica", lat: 9.75, lng: -83.75, flag: "🇨🇷", region: "Central America", continent: "Central America & Caribbean" },
  "dominican-republic": { label: "Dominican Rep.", lat: 18.74, lng: -70.16, flag: "🇩🇴", region: "Caribbean", continent: "Central America & Caribbean" },
  ecuador: { label: "Ecuador", lat: -1.83, lng: -78.18, flag: "🇪🇨", region: "South America", continent: "South America" },
  guatemala: { label: "Guatemala", lat: 15.78, lng: -90.23, flag: "🇬🇹", region: "Central America", continent: "Central America & Caribbean" },
  guyana: { label: "Guyana", lat: 4.86, lng: -58.93, flag: "🇬🇾", region: "South America", continent: "South America" },
  haiti: { label: "Haiti", lat: 18.97, lng: -72.29, flag: "🇭🇹", region: "Caribbean", continent: "Central America & Caribbean" },
  honduras: { label: "Honduras", lat: 15.20, lng: -86.24, flag: "🇭🇳", region: "Central America", continent: "Central America & Caribbean" },
  mexico: { label: "Mexico", lat: 23.63, lng: -102.55, flag: "🇲🇽", region: "North America", continent: "North America" },
  nicaragua: { label: "Nicaragua", lat: 12.87, lng: -85.21, flag: "🇳🇮", region: "Central America", continent: "Central America & Caribbean" },
  panama: { label: "Panama", lat: 8.54, lng: -80.78, flag: "🇵🇦", region: "Central America", continent: "Central America & Caribbean" },
  paraguay: { label: "Paraguay", lat: -23.44, lng: -58.44, flag: "🇵🇾", region: "South America", continent: "South America" },
  peru: { label: "Peru", lat: -9.19, lng: -75.02, flag: "🇵🇪", region: "South America", continent: "South America" },
  suriname: { label: "Suriname", lat: 3.92, lng: -56.03, flag: "🇸🇷", region: "South America", continent: "South America" },
  venezuela: { label: "Venezuela", lat: 6.42, lng: -66.59, flag: "🇻🇪", region: "South America", continent: "South America" },

  // ── Europe ──
  albania: { label: "Albania", lat: 41.15, lng: 20.17, flag: "🇦🇱", region: "Southeast Europe", continent: "Europe" },

  // ── Oceania ──
  "papua-new-guinea": { label: "Papua New Guinea", lat: -6.31, lng: 143.96, flag: "🇵🇬", region: "Melanesia", continent: "Oceania" },
  "solomon-islands": { label: "Solomon Is.", lat: -9.65, lng: 160.16, flag: "🇸🇧", region: "Melanesia", continent: "Oceania" },
  vanuatu: { label: "Vanuatu", lat: -15.38, lng: 166.96, flag: "🇻🇺", region: "Melanesia", continent: "Oceania" },
} as const;

export const DESTINATION_LIST = Object.keys(SUPPORTED_COUNTRIES) as Array<
  keyof typeof SUPPORTED_COUNTRIES
>;

export type CountrySlug = keyof typeof SUPPORTED_COUNTRIES;
